#!/usr/bin/env python
# -*- coding: utf-8 -*- 

"""
A phoneme encoding inspired by the ALINE algorithm and ASJP encodings.
Notes:
Language-dependent features, like syllabic/non-syllabic contrasts, and
lax-tense contrasts, are not represented as the features.
"""
multivalued_features = {'place': {
							'bilabial': 100,
							'labiodental': 95,
							'dental': 90,
							'alveolar': 85,
							'postalveolar': 80,
							'retroflex': 75,
							'alveolo-palatal': 75,
							'palato-alveolar': 70,
							'palatal': 60,
							'velar': 50,
							'uvular': 40,
							'pharyngeal': 20,
							'glottal': 0,
							#vowels
							'front-vowel': 100,
							'central-vowel': 50,
							'back-vowel': 0
							},
						'manner': {
							'stop': 100,
							'trill': 80,
							'tap': 70,
							'affricate': 60,
							'fricative': 50,
							'approximant': 30,
							#vowels
							'high-vowel': 20,
							'mid-vowel': 10,
							'low-vowel': 0
							},
						'tone': {
							'high': 100,
							'rising': 75,
							'mid': 50,
							'falling': 25,
							'low': 0,
							'default': 50
							},
						'voice': {
							'voiced': 100,
							'breathy': 75,
							'voiceless': 50,
							'ejective': 25,
							'aspirated': 0
							},
						'length': {
							'long': 100,
							'half-long': 75,
							'default': 50,
							'extra-short': 25
							}
						}

ipa_symbols = { #vowels
				u'i': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ì': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['low'],
					'length': multivalued_features['length']['default'],
					'round': 0, 
					'nasal': 0,
                    'lateral': 0},
				u'í': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['high'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'î': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['falling'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ǐ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['rising'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ĩ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 100,
                    'lateral': 0},
				u'ī': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['mid'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ĭ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['extra-short'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'y': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ɪ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ʏ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ɨ': {'place': multivalued_features['place']['central-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ʉ': {'place': multivalued_features['place']['central-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ʊ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ɯ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'u': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ù': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['low'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ú': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['high'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'û': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['falling'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ǔ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['rising'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ũ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 100,
                    'lateral': 0},
				u'ŭ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['high-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['extra-short'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'e': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'é': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['high'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ê': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['falling'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ē': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['mid'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ě': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['rising'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ẽ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 100,
                    'lateral': 0},
				u'ø': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ɘ': {'place': multivalued_features['place']['central-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ɵ': {'place': multivalued_features['place']['central-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				#0xc7 0x9d
				u'ǝ': {'place': multivalued_features['place']['central-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 50,
					'nasal': 0,
                    'lateral': 0},
				#0xc9 0x99
				u'ə': {'place': multivalued_features['place']['central-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 50,
					'nasal': 0,
                    'lateral': 0},
				u'ɤ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'o': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ó': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['high'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
                u'ǒ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['rising'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ô': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['falling'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'õ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 100,
                    'lateral': 0},
				u'ō': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['mid'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ɛ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'œ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'æ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ɜ': {'place': multivalued_features['place']['central-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ɞ': {'place': multivalued_features['place']['central-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ɐ': {'place': multivalued_features['place']['central-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 50,
					'nasal': 0,
                    'lateral': 0},
				u'ʌ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ɔ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['mid-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'a': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['low-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'á': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['low-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['high'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'â': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['low-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['falling'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ã': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['low-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 100,
                    'lateral': 0},
				u'ǎ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['low-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['rising'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ā': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['low-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['mid'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ɶ': {'place': multivalued_features['place']['front-vowel'],
					'manner': multivalued_features['manner']['low-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				u'ɑ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['low-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 0,
					'nasal': 0,
                    'lateral': 0},
				u'ɒ': {'place': multivalued_features['place']['back-vowel'],
					'manner': multivalued_features['manner']['low-vowel'],
					'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'round': 100,
					'nasal': 0,
                    'lateral': 0},
				#consonants
				u'p': {'place': multivalued_features['place']['bilabial'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
				u'b': {'place': multivalued_features['place']['bilabial'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u't': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'd': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'ʈ': {'place': multivalued_features['place']['retroflex'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'ɖ': {'place': multivalued_features['place']['retroflex'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'c': {'place': multivalued_features['place']['palatal'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'č': {'place': multivalued_features['place']['palatal'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['rising'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'ɟ': {'place': multivalued_features['place']['palatal'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'k': {'place': multivalued_features['place']['velar'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	#0x67
		       	u'g': {'place': multivalued_features['place']['velar'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	#0xc9 0xa1
		       	u'ɡ': {'place': multivalued_features['place']['velar'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'q': {'place': multivalued_features['place']['uvular'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'ɢ': {'place': multivalued_features['place']['uvular'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'ʔ': {'place': multivalued_features['place']['glottal'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
		       	u'm': {'place': multivalued_features['place']['bilabial'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 100,
                    'lateral': 0},
                u'ɱ': {'place': multivalued_features['place']['labiodental'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 100,
                    'lateral': 0},
                u'n': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 100,
                    'lateral': 0},
                u'ɳ': {'place': multivalued_features['place']['retroflex'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 100,
                    'lateral': 0},
                u'ɲ': {'place': multivalued_features['place']['palatal'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 100,
                    'lateral': 0},
                u'ŋ': {'place': multivalued_features['place']['velar'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 100,
                    'lateral': 0},
                u'ɴ': {'place': multivalued_features['place']['uvular'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 100,
                    'lateral': 0},
                u'ʙ': {'place': multivalued_features['place']['bilabial'],
		       		'manner': multivalued_features['manner']['trill'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'r': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['trill'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ᵲ': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['trill'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ṙ': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['trill'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʀ': {'place': multivalued_features['place']['uvular'],
		       		'manner': multivalued_features['manner']['trill'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ⱱ': {'place': multivalued_features['place']['labiodental'],
		       		'manner': multivalued_features['manner']['tap'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɾ': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['tap'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɽ': {'place': multivalued_features['place']['retroflex'],
		       		'manner': multivalued_features['manner']['tap'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɸ': {'place': multivalued_features['place']['bilabial'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'β': {'place': multivalued_features['place']['bilabial'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'f': {'place': multivalued_features['place']['labiodental'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'v': {'place': multivalued_features['place']['labiodental'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ṽ': {'place': multivalued_features['place']['labiodental'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 100,
                    'lateral': 0},
                u'θ': {'place': multivalued_features['place']['dental'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ð': {'place': multivalued_features['place']['dental'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'δ': {'place': multivalued_features['place']['dental'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u's': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'š': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['rising'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'z': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ž': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['rising'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʃ': {'place': multivalued_features['place']['postalveolar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʒ': {'place': multivalued_features['place']['postalveolar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʂ': {'place': multivalued_features['place']['retroflex'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʐ': {'place': multivalued_features['place']['retroflex'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ç': {'place': multivalued_features['place']['palatal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʝ': {'place': multivalued_features['place']['palatal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'x': {'place': multivalued_features['place']['velar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɣ': {'place': multivalued_features['place']['velar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'χ': {'place': multivalued_features['place']['uvular'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʁ': {'place': multivalued_features['place']['uvular'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ħ': {'place': multivalued_features['place']['pharyngeal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʕ': {'place': multivalued_features['place']['pharyngeal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'h': {'place': multivalued_features['place']['glottal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɦ': {'place': multivalued_features['place']['glottal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɬ': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 100},
                u'ł': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 100},
                u'ɮ': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 100},
                u'ʋ': {'place': multivalued_features['place']['labiodental'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɹ': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɻ': {'place': multivalued_features['place']['retroflex'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'j': {'place': multivalued_features['place']['palatal'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ǰ': {'place': multivalued_features['place']['palatal'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['rising'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɰ': {'place': multivalued_features['place']['velar'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'l': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 100},
                u'ɫ': {'place': (multivalued_features['place']['alveolar']+multivalued_features['place']['velar'])/2,
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 100},
                u'ɭ': {'place': multivalued_features['place']['retroflex'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 100},
                u'ʎ': {'place': multivalued_features['place']['palatal'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 100},
                u'ʟ': {'place': multivalued_features['place']['velar'],
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 100},
                u'ʍ': {'place': (multivalued_features['place']['bilabial']+multivalued_features['place']['velar'])/2,
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'w': {'place': (multivalued_features['place']['bilabial']+multivalued_features['place']['velar'])/2,
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɥ': {'place': (multivalued_features['place']['bilabial']+multivalued_features['place']['palatal'])/2,
		       		'manner': multivalued_features['manner']['approximant'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʜ': {'place': multivalued_features['place']['pharyngeal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʢ': {'place': multivalued_features['place']['pharyngeal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʡ': {'place': multivalued_features['place']['pharyngeal'],
		       		'manner': multivalued_features['manner']['stop'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɕ': {'place': multivalued_features['place']['alveolo-palatal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʑ': {'place': multivalued_features['place']['alveolo-palatal'],
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ɺ': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['tap'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 100},
                u'ɧ': {'place': (multivalued_features['place']['postalveolar']+multivalued_features['place']['velar'])/2,
		       		'manner': multivalued_features['manner']['fricative'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʧ': {'place': multivalued_features['place']['palato-alveolar'],
		       		'manner': multivalued_features['manner']['affricate'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʤ': {'place': multivalued_features['place']['palato-alveolar'],
		       		'manner': multivalued_features['manner']['affricate'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʦ': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['affricate'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʣ': {'place': multivalued_features['place']['alveolar'],
		       		'manner': multivalued_features['manner']['affricate'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʨ': {'place': multivalued_features['place']['alveolo-palatal'],
		       		'manner': multivalued_features['manner']['affricate'],
		       		'voice': multivalued_features['voice']['voiceless'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0},
                u'ʥ': {'place': multivalued_features['place']['alveolo-palatal'],
		       		'manner': multivalued_features['manner']['affricate'],
		       		'voice': multivalued_features['voice']['voiced'],
					'tone': multivalued_features['tone']['default'],
					'length': multivalued_features['length']['default'],
					'nasal': 0,
                    'lateral': 0}
                }

#diacritics that replace features of the preceding symbol
ipa_diacritics_replace = {u'̥': ('voice', multivalued_features['voice']['voiceless']),
                		  u'̊': ('voice', multivalued_features['voice']['voiceless']),
                		  u'ʰ': ('voice', multivalued_features['voice']['aspirated']),
                		  u'ʱ': ('voice', multivalued_features['voice']['breathy']),
                		  u'ʹ': ('voice', multivalued_features['voice']['ejective']),
                		  u'‘': ('voice', multivalued_features['voice']['ejective']),
                		  u'’': ('voice', multivalued_features['voice']['ejective']),
                		  u'̜': ('round', 50),
                		  u'ʲ': ('place', multivalued_features['place']['palatal']),
                		  u'ʷ': ('place', multivalued_features['place']['bilabial']),
		                  u'ˠ': ('place', multivalued_features['place']['velar']),
          		          u'ˤ': ('place', multivalued_features['place']['pharyngeal']),
		                  u'̴': ('place', (multivalued_features['place']['pharyngeal']+multivalued_features['place']['velar'])/2),
          		          u'ˀ': ('place', multivalued_features['place']['glottal']),
		                  u'̪': ('place', multivalued_features['place']['dental']),
          		          u'̻': ('place', multivalued_features['place']['alveolar']),
						  u'̤': ('place', multivalued_features['place']['central-vowel']),
		                  u'ⁿ': ('nasal', 100),
          		          u'̃': ('nasal', 100),
                		  u'́': ('tone', multivalued_features['tone']['high']),
		                  u'̄': ('tone', multivalued_features['tone']['mid']),
          		          u'̀': ('tone', multivalued_features['tone']['low']),
                		  u'̌': ('tone', multivalued_features['tone']['rising']),
		                  u'̂': ('tone', multivalued_features['tone']['falling']),
            		      u'̑': ('tone', multivalued_features['tone']['falling']),
						  u'ː': ('length', multivalued_features['length']['long']),
						  u':': ('length', multivalued_features['length']['long']),
						  u'ˑ': ('length', multivalued_features['length']['half-long']),
						  u'̆': ('length', multivalued_features['length']['extra-short'])
						  }

#diacritics that modify features of the preceding symbol
ipa_diacritics_modify = {u'̝': ('manner', 20),
						 u'̞': ('manner', -20),
						 u'̟': ('place', 20),
						 u'̠': ('place', -20)
						 }

#join the preceding and following symbols for double articulation
ipa_joining_bars = set([u'͜', u'͡']) 

#split the representation to multiple words
ipa_delimiters = u',|/|;'
				